### ISSUE TITLE
Using multiple sensors

### ISSUE THREAD

**Issue by basvuijk** [simondlevy/MB1242#1]
I would like to be able to read multiple sensors. This is likely to be possible since the implementation of the i2c bus. But I can't get it to work. 

I've tried changing the 'getDistance' and 'attempt_Write' piece of the code but it is nog working like I had in mind. 

```
 int MB1242::getDistance(int sensorAddress)
{
	if (this->state == 0){
		attempt_write(sensorAdress)
			this->state = 1;
	}
	else {
		uint8_t bytes[2];
			Wire.requestFrom(sensorAddress, 2);
			if (Wire.available() == 2){
				bytes[0] = Wire.read();
				bytes[1] = Wire.read();
				this->distance = (bytes[0] << 8) + bytes[1];
				this->state = 0;
			}
	}
	
	return this-distance;
} 
```

```
bool MB1242::attempt_write(int sensorAddress)
{
    Wire.beginTransmission(sensorAddress);
    Wire.write(0x51);
    return !Wire.endTransmission();
}
```

That's how I've currently implemented it, but it isn't working. 

This is the header file: 
```
 class MB1242 {

    private:

        static const int DFLT_ADDR = 0x70;

        int addr;
        int state;
        int distance;
        unsigned int time;

        bool attempt_write(int sensorAddress);

    public:

        void begin(unsigned char address=DFLT_ADDR);

        static void changeAddress(unsigned char oldaddr, unsigned char newaddr);

        int getDistance(int sensorAddress);
}; 
```

**Comment by simondlevy** [comment]
I set things up so you don't have to modify the internal code.  Instead, you simply call the begin() method with the desired I^2C address (default=0x70):

MB1242 sonar1;
MB1242 sonar2;
// etc.

sonar1.begin(0x70);
sonar2.begin(0x72);
// etc.

To set the address, you can use [this sketch](https://github.com/simondlevy/MB1242/tree/master/examples/changeaddress).
